backend:
  name: git-gateway
  branch: main

media_folder: images/uploads
public_folder: /images/uploads

collections:
  - name: produits
    label: Produits
    folder: content/produits
    create: true
    fields:
      - { name: nom, label: Nom, widget: string }
      - { name: prix, label: Prix, widget: number, default: 0 }
      - { name: disponible, label: Disponible, widget: boolean, default: true }
      - { name: image, label: Image, widget: image, required: false }
