backend:
  name: test-repo
  repo: SBM2323/mini-shop
  branch: main

collections:
  - name: produits
    label: Produits
    folder: content/produits
    create: true
    fields:
      - { name: nom, label: Nom, widget: string }
      - { name: prix, label: Prix, widget: number }
